name: CI

on:
  push:
    branches: master

jobs:
  test:
    name: test w/ Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7","3.8","3.9"]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install nox
      - run: nox
        env:
          PYTHONDEVMODE: 1
      - uses: codecov/codecov-action@v1
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cov.xml

  release:
    name: Publish to pypi
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install flit
      - name: Flit publish
        env:
          FLIT_USERNAME: "__token__"
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          FLIT_INDEX_URL: "https://upload.pypi.org/legacy/"
        run: flit publish
